### ISSUE TITLE
How can I start the app

### ISSUE THREAD

**Issue by rrfaria** [ongspxm/iqo2#1]
good job but I couldn't start the app.
Could you help me please write some guide how to first start the app just to test?
I tried set ssid and  node index.js 
but nothing happens

I'll try use brain.js to implement machine learning to make my trades so if your code works will help me a lot

**Comment by eortigoza5** [comment]
I have same issue
![image](https://user-images.githubusercontent.com/36522837/53673779-63320a80-3c68-11e9-8a3e-0f7fae8cf1f4.png)

ws.setCmd('f_activeCommissionChange', (obj) => {
   ^

TypeError: Cannot read property 'setCmd' of null
    at Object.<anonymous> (E:\DUKA_TICK\IQOPTION_GITHUB\iqoption2\iqo2-master\index.js:106:4)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by victorfds** [comment]
Same issue here.

**Comment by papalardo** [comment]
Same issue here.

**Comment by eialanjones** [comment]
- yarn add dotenv

iqoSocket.js

const { parsed } = require('dotenv').config();

const { SSID } = parsed;
